### ISSUE TITLE
Moving on

### ISSUE THREAD

**Issue by mightyiam** [jmanero/auto-package#10]
@jmanero I've submitted a few PRs and an issue.

Will you review or would you prefer me to fork or take charge?

**Comment by jmanero** [comment]
Will look through these when I get out of work tonight. I seem to have not been getting notifications on PRs for a bit.

**Comment by mightyiam** [comment]
Great. I'm just about to use in yet another package.

**Comment by mightyiam** [comment]
Thank you very much, @jmanero . I'm really happy about this. This is one of those packages that someone had to eventually make but no–one did until someone did. And that's you.

So thank you.
