### ISSUE TITLE
Methods for setting provided values are mostly confusion

### ISSUE THREAD

**Issue by mightyiam** [jmanero/auto-package#9]
`name()',`description()`, etc. don't serve much purpose.

If all they do is set the value of `Package.package[foo]` then

``` js
Package.name('foo')
// doesn't have much advantage over simply
Package.package.name = 'foo'
```

But because there are a limited amount of these methods, I must remember which ones exist.

This remembering is just a burden, for me, currently.

I suggest that methods also exist if they do something more than setting the provided value as it is.

`Package.github_repo` is a useful method to me, as it does something.

**Comment by jmanero** [comment]
Hmmm, I think you're correct here. Just rendering the module root with some validation is probably a better interface:

```
myPackage.name = '...';
myPackage.author = '...';
myPackage.versionFile();
myPackage.depends('foo');
```

I'll try to change this soon. In the mean time, I'm cuttint 0.2.0 and pushing to NPM

**Comment by mightyiam** [comment]
I think that since we changed the API since last release, the major version should be incremented. I've never been a fan of `0.*` releases.

**Comment by mightyiam** [comment]
Also, there's a namespace issue here.

If the exports root ends up as the JSON, then any method we add there is a potential collision with some property name that the user is going to desire

``` js
var auto = require('auto-package')
var object = auto.object

object.name = 'fun-stuff'
object.description = 'A collection of fun stuff'
auto.versionFile()
auto.depends('time')
auto.devDepends('vision')
```

How about that as a guideline for the API?

**Comment by mightyiam** [comment]
Excuse my lack of semicolons. I'm using [Standard Style](https://github.com/feross/standard).

**Comment by jmanero** [comment]
That's what I'm thinking. Helpers can't shadow keys in the package.json
spec. I'm going to iterate a couple more times on the 0.x line and cut
1.0.0 once some semblance of reverse compatibility have been implemented

**Comment by mightyiam** [comment]
Nice job, there, with the schemes, @jmanero. Tests and all!

**Comment by jmanero** [comment]
Thanks. Will try to get some README updates out soon
